;generated at Mon 11 Dec 23:20:15 UTC 2023, PrusaFirmwareBuddy commit=15d5ae0b317a37b69b8e7a4720711b962c25b57d, script source https://github.com/nvtkaszpir/3d-print
M331 24VVoltage ;metric type FLOAT - src/common/app_metrics.cpp
M331 5VVoltage ;metric type FLOAT - src/common/app_metrics.cpp
M331 active_extruder ;metric type INTEGER - src/common/app_metrics.cpp
M331 adj_z ;metric type FLOAT - src/common/app_metrics.cpp
M331 app_start ;metric type EVENT - src/common/appmain.cpp
M331 bed_curr ;metric type CUSTOM - src/puppies/modular_bed.cpp
M331 bedlet_curr ;metric type CUSTOM - src/puppies/modular_bed.cpp
M331 bedlet_pwm ;metric type CUSTOM - src/puppies/modular_bed.cpp
M331 bedlet_reg ;metric type CUSTOM - src/puppies/modular_bed.cpp
M331 bedlet_state ;metric type CUSTOM - src/puppies/modular_bed.cpp
M331 bedlet_target ;metric type CUSTOM - src/puppies/modular_bed.cpp
M331 bedlet_temp ;metric type CUSTOM - src/puppies/modular_bed.cpp
M331 bed_mcu_temp ;metric type FLOAT - src/puppies/modular_bed.cpp
M331 bed_pwm ;metric type INTEGER - src/common/hwio_buddy_2209_02.cpp
M331 bed_state ;metric type INTEGER - src/puppies/modular_bed.cpp
M331 buddy_bom ;metric type STRING - src/common/app_metrics.cpp
M331 buddy_revision ;metric type STRING - src/common/app_metrics.cpp
M331 buddy_t ;metric type INTEGER - src/puppies/time_sync.cpp
M331 cpu_usage ;metric type FLOAT - doc/metrics.md
M331 cpu_usage ;metric type INTEGER - src/common/appmain.cpp
M331 crash_length ;metric type CUSTOM - src/common/marlin_server.cpp
M331 crash ;metric type CUSTOM - lib/Marlin/Marlin/src/feature/prusa/crash_recovery.cpp
M331 crash_repeated ;metric type EVENT - lib/Marlin/Marlin/src/feature/prusa/crash_recovery.cpp
M331 crash_stat ;metric type CUSTOM - lib/Marlin/Marlin/src/feature/prusa/crash_recovery.cpp
M331 cur_mmu_imp ;metric type FLOAT - src/common/app_metrics.cpp
M331 curr_inp ;metric type FLOAT - src/common/app_metrics.cpp
M331 curr_inp_raw ;metric type INTEGER - src/common/app_metrics.cpp
M331 curr_nozz ;metric type FLOAT - src/common/app_metrics.cpp
M331 curr_nozz_raw ;metric type INTEGER - src/common/app_metrics.cpp
M331 dwarf_board_temp ;metric type INTEGER - src/common/app_metrics.cpp
M331 dwarf_fast_refresh_delay ;metric type INTEGER - src/puppies/Dwarf.cpp
M331 dwarf_heat_curr ;metric type CUSTOM - src/puppies/Dwarf.cpp
M331 dwarf_mcu_temp ;metric type INTEGER - src/common/app_metrics.cpp
M331 dwarf_parked_raw ;metric type CUSTOM - src/puppies/Dwarf.cpp
M331 dwarf_picked_raw ;metric type CUSTOM - src/puppies/Dwarf.cpp
M331 dwarfs_board_temp ;metric type CUSTOM - src/common/app_metrics.cpp
M331 dwarfs_mcu_temp ;metric type CUSTOM - src/common/app_metrics.cpp
M331 eeprom_write ;metric type EVENT - src/common/st25dv64k.cpp
M331 esp_in ;metric type CUSTOM - lib/WUI/espif.cpp
M331 esp_out ;metric type CUSTOM - lib/WUI/espif.cpp
M331 eth_in ;metric type CUSTOM - lib/WUI/ethernetif.c
M331 eth_out ;metric type CUSTOM - lib/WUI/ethernetif.c
M331 excite_freq ;metric type FLOAT - lib/Marlin/Marlin/src/gcode/calibrate/M958.cpp
M331 fan_hbr_speed ;metric type INTEGER - src/common/app_metrics.cpp
M331 fan ;metric type CUSTOM - src/common/fanctl/CFanCtlCommon.cpp
M331 fan_speed ;metric type INTEGER - src/common/app_metrics.cpp
M331 filament ;metric type STRING - src/common/app_metrics.cpp
M331 freq_gain ;metric type CUSTOM - lib/Marlin/Marlin/src/gcode/calibrate/M958.cpp
M331 fsensor ;metric type CUSTOM - src/common/filament_sensor_adc.cpp
M331 fsensor_raw ;metric type CUSTOM - src/common/filament_sensor_adc.cpp
M331 fw_version ;metric type STRING - src/common/app_metrics.cpp
M331 g425_cen ;metric type CUSTOM - src/marlin_stubs/G425.cpp
M331 g425_off ;metric type CUSTOM - src/marlin_stubs/G425.cpp
M331 g425_rxy ;metric type CUSTOM - src/marlin_stubs/G425.cpp
M331 g425_rz ;metric type CUSTOM - src/marlin_stubs/G425.cpp
M331 g425_xy_dev ;metric type FLOAT - src/marlin_stubs/G425.cpp
M331 g425_xy ;metric type CUSTOM - src/marlin_stubs/G425.cpp
M331 g425_z ;metric type CUSTOM - src/marlin_stubs/G425.cpp
M331 gcode ;metric type STRING - src/marlin_stubs/gcode.cpp
M331 gui_loop_dur ;metric type INTEGER - src/gui/gui_time.cpp
M331 hbr_fan_act ;metric type INTEGER - src/common/fanctl/CFanCtlCommon.cpp
M331 heap_free ;metric type INTEGER - doc/metrics.md
M331 heap ;metric type CUSTOM - doc/metrics.md
M331 heap ;metric type CUSTOM - src/common/app_metrics.cpp
M331 heap ;metric type INTEGER - doc/metrics.md
M331 heap_total ;metric type INTEGER - doc/metrics.md
M331 heater_enabled ;metric type INTEGER - src/common/app_metrics.cpp
M331 heating_model_discrepancy ;metric type INTEGER - lib/Marlin/Marlin/src/module/temperature.cpp
M331 home_diff ;metric type CUSTOM - lib/Marlin/Marlin/src/module/motion.cpp
M331 ipos_x ;metric type INTEGER - src/common/app_metrics.cpp
M331 ipos_y ;metric type INTEGER - src/common/app_metrics.cpp
M331 ipos_z ;metric type INTEGER - src/common/app_metrics.cpp
M331 is_printing ;metric type INTEGER - src/common/app_metrics.cpp
M331 loadcell_age ;metric type INTEGER - src/common/loadcell.cpp
M331 loadcell_hp ;metric type FLOAT - src/common/loadcell.cpp
M331 loadcell_hysteresis ;metric type FLOAT - src/marlin_stubs/gcode.cpp
M331 loadcell ;metric type CUSTOM - src/common/loadcell.cpp
M331 loadcell_scale ;metric type FLOAT - src/marlin_stubs/gcode.cpp
M331 loadcell_threshold_cont ;metric type FLOAT - src/marlin_stubs/gcode.cpp
M331 loadcell_threshold ;metric type FLOAT - src/marlin_stubs/gcode.cpp
M331 loadcell_value ;metric type FLOAT - src/common/loadcell.cpp
M331 loadcell_xy ;metric type FLOAT - src/common/loadcell.cpp
M331 maintask_loop ;metric type EVENT - src/common/appmain.cpp
M331 media_prefetched ;metric type INTEGER - src/common/media.cpp
M331 mmu_comm ;metric type STRING - src/mmu2/mmu2_log.cpp
M331 modbus_reqfail ;metric type EVENT - src/puppies/PuppyModbus.cpp
M331 nozzle_pwm ;metric type INTEGER - src/common/hwio_buddy_2209_02.cpp
M331 oc_inp ;metric type INTEGER - src/common/app_metrics.cpp
M331 oc_nozz ;metric type INTEGER - src/common/app_metrics.cpp
M331 points_dropped ;metric type INTEGER - src/common/metric.cpp
M331 pos_x ;metric type FLOAT - src/common/app_metrics.cpp
M331 pos_y ;metric type FLOAT - src/common/app_metrics.cpp
M331 pos_z ;metric type FLOAT - src/common/app_metrics.cpp
M331 power_panic ;metric type EVENT - src/common/marlin_server.cpp
M331 print_fan_act ;metric type INTEGER - src/common/fanctl/CFanCtlCommon.cpp
M331 print_filename ;metric type STRING - src/common/app_metrics.cpp
M331 probe_analysis ;metric type CUSTOM - lib/Marlin/Marlin/src/module/probe.cpp
M331 probe_start ;metric type EVENT - lib/Marlin/Marlin/src/module/probe.cpp
M331 probe_window ;metric type CUSTOM - src/common/probe_analysis.hpp
M331 probe_z_diff ;metric type CUSTOM - lib/Marlin/Marlin/src/module/probe.cpp
M331 probe_z ;metric type CUSTOM - lib/Marlin/Marlin/src/module/probe.cpp
M331 puppy_adrif ;metric type CUSTOM - src/puppies/time_sync.cpp
M331 puppy_aoff ;metric type CUSTOM - src/puppies/time_sync.cpp
M331 puppy_drift ;metric type CUSTOM - src/puppies/time_sync.cpp
M331 puppy_off ;metric type CUSTOM - src/puppies/time_sync.cpp
M331 puppy_t ;metric type CUSTOM - src/puppies/time_sync.cpp
M331 runtime ;metric type CUSTOM - src/common/app_metrics.cpp
M331 Sandwitch5VCurrent ;metric type FLOAT - src/common/app_metrics.cpp
M331 side_fsensor ;metric type CUSTOM - src/common/filament_sensor_adc.cpp
M331 side_fsensor_raw ;metric type CUSTOM - src/common/filament_sensor_adc.cpp
M331 splitter_5V_current ;metric type FLOAT - src/common/app_metrics.cpp
M331 stack ;metric type CUSTOM - src/common/app_metrics.cpp
M331 sync_rt ;metric type CUSTOM - src/puppies/time_sync.cpp
M331 temp_bed ;metric type FLOAT - src/common/app_metrics.cpp
M331 temp_brd ;metric type FLOAT - src/common/app_metrics.cpp
M331 temp_chamber ;metric type FLOAT - src/common/app_metrics.cpp
M331 temp_hbr ;metric type CUSTOM - src/common/app_metrics.cpp
M331 temp_mcu ;metric type INTEGER - src/common/app_metrics.cpp
M331 temp_noz ;metric type CUSTOM - src/common/app_metrics.cpp
M331 temp_sandwich ;metric type FLOAT - src/common/app_metrics.cpp
M331 temp_splitter ;metric type FLOAT - src/common/app_metrics.cpp
M331 tk_accel ;metric type CUSTOM - lib/Marlin/Marlin/src/gcode/calibrate/M958.cpp
M331 tmc_read ;metric type CUSTOM - src/common/trinamic.cpp
M331 tmc_sg_e ;metric type INTEGER - src/common/thread_measurement.cpp
M331 tmc_sg_x ;metric type INTEGER - src/common/thread_measurement.cpp
M331 tmc_sg_y ;metric type INTEGER - src/common/thread_measurement.cpp
M331 tmc_sg_z ;metric type INTEGER - src/common/thread_measurement.cpp
M331 tmc_write ;metric type CUSTOM - src/common/trinamic.cpp
M331 ttemp_bed ;metric type INTEGER - src/common/app_metrics.cpp
M331 ttemp_noz ;metric type CUSTOM - src/common/app_metrics.cpp
M331 usbh_err_cnt ;metric type INTEGER - src/common/media.cpp
M331 val_xyz ;metric type INTEGER - src/common/metric.h
M331 volt_bed ;metric type FLOAT - src/common/app_metrics.cpp
M331 volt_bed_raw ;metric type INTEGER - src/common/app_metrics.cpp
M331 volt_nozz ;metric type FLOAT - src/common/app_metrics.cpp
M331 volt_nozz_raw ;metric type INTEGER - src/common/app_metrics.cpp
M331 xlbuddy5VCurrent ;metric type FLOAT - src/common/app_metrics.cpp
