{
 "title": "Tensor Beam",
 "tags": [ "prusa" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "a", "label": "a", "query": "${VAR_A}" },
   { "name": "b", "label": "b", "query": "${VAR_B}" },
   { "name": "spool_weight", "query": "290" },
   { "name": "density", "query": "1.29" },
   { "name": "diameter", "query": "1.75" },
   { "name": "dolly", "query": "95" },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Filament weight left",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "massg" } },
   "targets": [
    {
     "expr": "((homeassistant_sensor_state{entity=\"sensor.esp32_devkit_v4_9e8360_hx711_value\"}-$b)/$a)-$spool_weight-$dolly",
     "legendFormat": "weight (g)"
    },
    {
     "expr": "((avg_over_time(homeassistant_sensor_state{entity=\"sensor.esp32_devkit_v4_9e8360_hx711_value\"}[5m])-$b)/$a)-$spool_weight-$dolly",
     "legendFormat": "5m avg weight (g)"
    }
   ]
  },
  {
   "title": "Filament meters left",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "targets": [
    {
     "expr": "(((homeassistant_sensor_state{entity=\"sensor.esp32_devkit_v4_9e8360_hx711_value\"}-$b)/$a)-$spool_weight-$dolly)/($density*3.1415*$diameter*$diameter/4)",
     "legendFormat": "length (m)"
    },
    {
     "expr": "(((avg_over_time(homeassistant_sensor_state{entity=\"sensor.esp32_devkit_v4_9e8360_hx711_value\"}[5m])-$b)/$a)-$spool_weight-$dolly)/($density*3.1415*$diameter*$diameter/4)",
     "legendFormat": "5min avg length (m)"
    }
   ]
  },
  {
   "title": "Filament meters left",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((homeassistant_sensor_state{entity=\"sensor.esp32_devkit_v4_9e8360_hx711_value\"}-$b)/$a)-$spool_weight-$dolly)/($density*3.1415*$diameter*$diameter/4)",
     "legendFormat": "length (m)"
    },
    {
     "expr": "(((avg_over_time(homeassistant_sensor_state{entity=\"sensor.esp32_devkit_v4_9e8360_hx711_value\"}[5m])-$b)/$a)-$spool_weight-$dolly)/($density*3.1415*$diameter*$diameter/4)",
     "legendFormat": "5m avg ength (m)"
    }
   ]
  },
  {
   "title": "Info",
   "type": "text",
   "gridPos": { "h": 12, "w": 4, "x": 20, "y": 0 },
   "options": {
    "content": "**Spool Weight:**\nin grams:\n- 200 Prusa\n- 245 Rosa 3D\n- 255 Devil Design\n- 290 Fiberlogy\n\n**Density**\n- 1.27 Easy PETG Fiberlogy\n- 1.23 PETG Devil Design\n- 1.27 PETG Prusa\n- 1.29 PETG Rosa3D GLOW\n\n\n**Diameter**\n- 1.75 - standard"
   }
  },
  {
   "title": "Filament weight left",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "massg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((homeassistant_sensor_state{entity=\"sensor.esp32_devkit_v4_9e8360_hx711_value\"}-$b)/$a)-$spool_weight-$dolly",
     "legendFormat": "weight (g)"
    },
    {
     "expr": "((avg_over_time(homeassistant_sensor_state{entity=\"sensor.esp32_devkit_v4_9e8360_hx711_value\"}[5m])-$b)/$a)-$spool_weight-$dolly",
     "legendFormat": "5m avg weight (g)"
    }
   ]
  },
  {
   "title": "Raw data",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "RAW",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "homeassistant_sensor_state{entity=\"sensor.esp32_devkit_v4_9e8360_hx711_value\"}",
       "legendFormat": "weight"
      }
     ]
    },
    {
     "title": "RAW",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "homeassistant_sensor_state{entity=\"sensor.esp32_devkit_v4_9e8360_hx711_value\"}",
       "legendFormat": "weight"
      }
     ]
    },
    {
     "title": "Raw Weight",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "massg" } },
     "targets": [
      {
       "expr": "(homeassistant_sensor_state{entity=\"sensor.esp32_devkit_v4_9e8360_hx711_value\"}-$b)/$a",
       "legendFormat": "weight"
      }
     ]
    }
   ]
  }
 ]
}